name: Hello World

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - dev
          - prod

env:
  DEPLOYMENT_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/feature/test' && 'dev' || 'unknown' }}

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:

  #   - name: Hello world
  #     run: echo 'Hello world!'

  deployment:
    # needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: Deploy
      run: |
        echo "github.ref: ${{ github.ref }}"
        echo "variable: ${{ vars.MY_VARIABLE }}"