name: Hello World

on: 
  push:
    branches:
      - main
      - feature/*

env:
  DEPLOYMENT_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/feature/**' && 'dev' || 'unknown' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Hello world
      run: echo 'Hello world!'

  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ vars.DEPLOYMENT_ENVIRONMENT }}
    steps:
    - name: Deploy
      run: |
        echo "github.ref: ${{ github.ref }}"
        echo "variable: ${{ vars.MY_VARIABLE }}"